--- # condition yaml
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
        - name: install apache on debian
          command: apt-get install apache2 -y
          when: ansible_os_family=="Debian"
        - name: install apache on redhat
          command: yum install httpd -y
          when: ansible_os_family=="RedHat"