- hosts: demo # install tomcat7 in amazon linux 2
  connection: ssh
  become: yes
  tasks:
       - name: Install required packages
          yum:
           name:
             - java-17-amazon-corretto
           state: present

        - name: Install required packages
          yum:
           name:
             - java-17-amazon-corretto-devel
           state: present

        - name: Set JAVA_HOME environment variable
          lineinfile:
            dest: /etc/environment
            line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk'
            state: present


        - name: Create a Tomcat Directory
          file:
               path: /opt/tomcat
               mode: 755
               recurse: yes

        - name: download & unarchive tomcat7
          unarchive:
                    src: http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.86/bin/apache-tomcat-9.0.86.tar.gz
                    dest: /opt/tomcat
                    remote_src: yes
                    extra_opts: [--strip-components=1]

        - name: start tomcat services
          shell: nohup /opt/tomcat/bin/startup.sh
