--- # condition yaml
- hosts: dev-env
  connection: ssh
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
      become: yes

    - name: Set JAVA_HOME environment variable
      lineinfile:
        dest: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        state: present
        create: yes
      become: yes

    - name: Reload environment variables
      shell: . /etc/environment
      become: yes
